import {
  BookOpen,
  Star,
  Users,
  Rocket,
  Lightbulb,
  Code,
  MessageCircle,
  Music2,
  Trophy,
  Brain,
  Globe2,
  Palette,
  Heart,
  Leaf,
  Shield,
  Sword,
  CloudSun,
  Coffee,
  FlaskConical,
  GraduationCap,
  AlarmClock,
  CalendarDays,
  Sun,
  Moon,
  Umbrella,
  Atom,
  Beaker,
  Bug,
  Cat,
  Dog,
  Dice5,
  Eye,
  Feather,
  FileText,
  Film,
  Flag,
  Gamepad2,
  Ghost,
  GitBranch,
  GitCommit,
  Globe,
  Home,
  Laptop,
  Library,
  Lock,
  Magnet,
  Map,
  Mic,
  Monitor,
  MousePointer,
  Mountain,
  PenTool,
  Phone,
  PiggyBank,
  Pin,
  Pizza,
  Plug,
  Rainbow,
  Recycle,
  Scroll,
  Send,
  Server,
  Settings,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkle,
  Speech,
  SunMedium,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  TreePine,
  Wallet,
  Wand2,
  Wind,
  Wrench,
  UsersRound,
} from 'lucide-react';
import type { GroupAvatarOption } from './types';

export const defaultAvatar: GroupAvatarOption = {
  id: 'group',
  icon: UsersRound,
  color: 'text-blue-500',
  label: 'Group',
};

export const GROUP_AVATAR_OPTIONS: GroupAvatarOption[] = [
  { id: 'book', icon: BookOpen, color: 'text-blue-500', label: 'Book' },
  { id: 'star', icon: Star, color: 'text-yellow-400', label: 'Star' },
  { id: 'users', icon: Users, color: 'text-emerald-500', label: 'Users' },
  { id: 'rocket', icon: Rocket, color: 'text-pink-500', label: 'Rocket' },
  {
    id: 'lightbulb',
    icon: Lightbulb,
    color: 'text-amber-400',
    label: 'Lightbulb',
  },
  { id: 'code', icon: Code, color: 'text-gray-700', label: 'Code' },
  {
    id: 'message',
    icon: MessageCircle,
    color: 'text-indigo-500',
    label: 'Chat',
  },
  { id: 'music', icon: Music2, color: 'text-purple-500', label: 'Music' },
  { id: 'trophy', icon: Trophy, color: 'text-orange-400', label: 'Trophy' },
  { id: 'brain', icon: Brain, color: 'text-red-400', label: 'Brain' },
  { id: 'globe', icon: Globe2, color: 'text-sky-500', label: 'Global' },
  { id: 'palette', icon: Palette, color: 'text-fuchsia-500', label: 'Art' },
  { id: 'heart', icon: Heart, color: 'text-rose-500', label: 'Heart' },
  { id: 'leaf', icon: Leaf, color: 'text-green-600', label: 'Leaf' },
  { id: 'shield', icon: Shield, color: 'text-blue-700', label: 'Shield' },
  { id: 'sword', icon: Sword, color: 'text-violet-800', label: 'Sword' },
  { id: 'sun', icon: Sun, color: 'text-yellow-300', label: 'Sun' },
  { id: 'cloud', icon: CloudSun, color: 'text-cyan-400', label: 'Cloud' },
  { id: 'coffee', icon: Coffee, color: 'text-amber-700', label: 'Coffee' },
  { id: 'flask', icon: FlaskConical, color: 'text-teal-700', label: 'Science' },
  {
    id: 'graduation',
    icon: GraduationCap,
    color: 'text-black',
    label: 'Graduation',
  },
  { id: 'alarm', icon: AlarmClock, color: 'text-red-500', label: 'Alarm' },
  {
    id: 'calendar',
    icon: CalendarDays,
    color: 'text-green-800',
    label: 'Calendar',
  },
  { id: 'moon', icon: Moon, color: 'text-gray-400', label: 'Moon' },
  { id: 'umbrella', icon: Umbrella, color: 'text-sky-600', label: 'Umbrella' },
  { id: 'atom', icon: Atom, color: 'text-cyan-700', label: 'Atom' },
  { id: 'beaker', icon: Beaker, color: 'text-indigo-700', label: 'Beaker' },
  { id: 'bug', icon: Bug, color: 'text-red-700', label: 'Bug' },
  { id: 'cat', icon: Cat, color: 'text-orange-600', label: 'Cat' },
  { id: 'dog', icon: Dog, color: 'text-yellow-700', label: 'Dog' },
  { id: 'dice', icon: Dice5, color: 'text-purple-700', label: 'Dice' },
  { id: 'eye', icon: Eye, color: 'text-pink-300', label: 'Eye' },
  { id: 'feather', icon: Feather, color: 'text-emerald-300', label: 'Feather' },
  { id: 'file', icon: FileText, color: 'text-cyan-700', label: 'Document' },
  { id: 'film', icon: Film, color: 'text-fuchsia-700', label: 'Film' },
  { id: 'flag', icon: Flag, color: 'text-lime-600', label: 'Flag' },
  { id: 'gamepad', icon: Gamepad2, color: 'text-red-400', label: 'Game' },
  { id: 'ghost', icon: Ghost, color: 'text-gray-700', label: 'Ghost' },
  {
    id: 'git-branch',
    icon: GitBranch,
    color: 'text-purple-500',
    label: 'Branch',
  },
  {
    id: 'git-commit',
    icon: GitCommit,
    color: 'text-blue-900',
    label: 'Commit',
  },
  { id: 'globe1', icon: Globe, color: 'text-cyan-600', label: 'World' },
  { id: 'home', icon: Home, color: 'text-lime-700', label: 'Home' },
  { id: 'laptop', icon: Laptop, color: 'text-indigo-600', label: 'Laptop' },
  { id: 'library', icon: Library, color: 'text-green-700', label: 'Library' },
  { id: 'lock', icon: Lock, color: 'text-gray-700', label: 'Lock' },
  { id: 'magnet', icon: Magnet, color: 'text-pink-600', label: 'Magnet' },
  { id: 'map', icon: Map, color: 'text-green-600', label: 'Map' },
  { id: 'mic', icon: Mic, color: 'text-purple-400', label: 'Mic' },
  { id: 'monitor', icon: Monitor, color: 'text-blue-700', label: 'Monitor' },
  {
    id: 'mouse',
    icon: MousePointer,
    color: 'text-amber-700',
    label: 'Pointer',
  },
  { id: 'mountain', icon: Mountain, color: 'text-gray-500', label: 'Mountain' },
  { id: 'pen', icon: PenTool, color: 'text-green-400', label: 'Pen Tool' },
  { id: 'phone', icon: Phone, color: 'text-green-800', label: 'Phone' },
  { id: 'piggy', icon: PiggyBank, color: 'text-pink-400', label: 'Piggy Bank' },
  { id: 'pin', icon: Pin, color: 'text-cyan-500', label: 'Pin' },
  { id: 'pizza', icon: Pizza, color: 'text-orange-500', label: 'Pizza' },
  { id: 'plug', icon: Plug, color: 'text-sky-700', label: 'Plug' },
  { id: 'rainbow', icon: Rainbow, color: 'text-pink-400', label: 'Rainbow' },
  { id: 'recycle', icon: Recycle, color: 'text-green-700', label: 'Recycle' },
  { id: 'scroll', icon: Scroll, color: 'text-amber-300', label: 'Scroll' },
  { id: 'send', icon: Send, color: 'text-blue-700', label: 'Send' },
  { id: 'server', icon: Server, color: 'text-indigo-700', label: 'Server' },
  { id: 'settings', icon: Settings, color: 'text-gray-600', label: 'Settings' },
  {
    id: 'shopping',
    icon: ShoppingCart,
    color: 'text-orange-700',
    label: 'Shopping Cart',
  },
  { id: 'smile', icon: Smile, color: 'text-yellow-300', label: 'Smile' },
  {
    id: 'snowflake',
    icon: Snowflake,
    color: 'text-blue-300',
    label: 'Snowflake',
  },
  { id: 'sparkle', icon: Sparkle, color: 'text-indigo-300', label: 'Sparkle' },
  { id: 'speech', icon: Speech, color: 'text-pink-600', label: 'Speech' },
  {
    id: 'sun-medium',
    icon: SunMedium,
    color: 'text-orange-300',
    label: 'Sun Medium',
  },
  { id: 'target', icon: Target, color: 'text-red-600', label: 'Target' },
  {
    id: 'terminal',
    icon: Terminal,
    color: 'text-neutral-600',
    label: 'Terminal',
  },
  {
    id: 'thumbsup',
    icon: ThumbsUp,
    color: 'text-blue-500',
    label: 'Thumbs Up',
  },
  { id: 'timer', icon: Timer, color: 'text-emerald-400', label: 'Timer' },
  { id: 'tree', icon: TreePine, color: 'text-green-500', label: 'Pine Tree' },
  { id: 'wallet', icon: Wallet, color: 'text-yellow-700', label: 'Wallet' },
  { id: 'wand', icon: Wand2, color: 'text-purple-300', label: 'Wand' },
  { id: 'wind', icon: Wind, color: 'text-cyan-300', label: 'Wind' },
  { id: 'wrench', icon: Wrench, color: 'text-gray-700', label: 'Wrench' },
];
