import type { GroupAvatarOption } from './types';

// prettier-ignore
import { BookOpen, Star, Users, Rocket, Lightbulb, Code, MessageCircle, Music2, Trophy, Brain, Globe2, Palette, Heart, Leaf, Shield, Sword, CloudSun, Coffee, FlaskConical, GraduationCap, AlarmClock, CalendarDays, Sun, Moon, Umbrella, Atom, Beaker, Bug, Cat, Dog, Dice5, Eye, Feather, FileText, Film, Flag, Gamepad2, Ghost, GitBranch, GitCommit, Globe, Home, Laptop, Library, Lock, Magnet, Map, Mic, Monitor, MousePointer, Mountain, PenTool, Phone, PiggyBank, Pin, Pizza, Plug, Rainbow, Recycle, Scroll, Send, Server, Settings, ShoppingCart, Smile, Snowflake, Sparkle, Speech, SunMedium, Target, Terminal, ThumbsUp, Timer, TreePine, Wallet, Wand2, Wind, Wrench, UsersRound,
} from 'lucide-react';

export const defaultAvatar: GroupAvatarOption = {
  id: 'group',
  icon: UsersRound,
  color: 'text-[#3B82F6]',
  background: 'bg-[#DBEAFE]',
  label: 'Group',
};

// prettier-ignore
export const GROUP_AVATAR_OPTIONS: GroupAvatarOption[] = [
  { id: 'book', icon: BookOpen, color: 'text-[#3B82F6]', background: 'bg-[#DBEAFE]', label: 'Book' },
  { id: 'star', icon: Star, color: 'text-[#FACC15]', background: 'bg-[#FEF9C3]', label: 'Star' },
  { id: 'users', icon: Users, color: 'text-[#10B981]', background: 'bg-[#D1FAE5]', label: 'Users' },
  { id: 'rocket', icon: Rocket, color: 'text-[#EC4899]', background: 'bg-[#FCE7F3]', label: 'Rocket' },
  { id: 'lightbulb', icon: Lightbulb, color: 'text-[#FBBF24]', background: 'bg-[#FEF3C7]', label: 'Lightbulb' },
  { id: 'code', icon: Code, color: 'text-[#374151]', background: 'bg-[#E5E7EB]', label: 'Code' },
  { id: 'message', icon: MessageCircle, color: 'text-[#6366F1]', background: 'bg-[#E0E7FF]', label: 'Chat' },
  { id: 'music', icon: Music2, color: 'text-[#A855F7]', background: 'bg-[#F3E8FF]', label: 'Music' },
  { id: 'trophy', icon: Trophy, color: 'text-[#FB923C]', background: 'bg-[#FFEDD5]', label: 'Trophy' },
  { id: 'brain', icon: Brain, color: 'text-[#F87171]', background: 'bg-[#FEE2E2]', label: 'Brain' },
  { id: 'globe', icon: Globe2, color: 'text-[#0EA5E9]', background: 'bg-[#E0F2FE]', label: 'Global' },
  { id: 'palette', icon: Palette, color: 'text-[#D946EF]', background: 'bg-[#FAE8FF]', label: 'Art' },
  { id: 'heart', icon: Heart, color: 'text-[#F43F5E]', background: 'bg-[#FFE4E6]', label: 'Heart' },
  { id: 'leaf', icon: Leaf, color: 'text-[#16A34A]', background: 'bg-[#DCFCE7]', label: 'Leaf' },
  { id: 'shield', icon: Shield, color: 'text-[#1D4ED8]', background: 'bg-[#DBEAFE]', label: 'Shield' },
  { id: 'sword', icon: Sword, color: 'text-[#5B21B6]', background: 'bg-[#EDE9FE]', label: 'Sword' },
  { id: 'sun', icon: Sun, color: 'text-[#FDE047]', background: 'bg-[#FEFCE8]', label: 'Sun' },
  { id: 'cloud', icon: CloudSun, color: 'text-[#22D3EE]', background: 'bg-[#CFFAFE]', label: 'Cloud' },
  { id: 'coffee', icon: Coffee, color: 'text-[#92400E]', background: 'bg-[#FFFBEB]', label: 'Coffee' },
  { id: 'flask', icon: FlaskConical, color: 'text-[#0F766E]', background: 'bg-[#CCFBF1]', label: 'Science' },
  { id: 'graduation', icon: GraduationCap, color: 'text-[#000000]', background: 'bg-[#F5F5F5]', label: 'Graduation' },
  { id: 'alarm', icon: AlarmClock, color: 'text-[#EF4444]', background: 'bg-[#FEE2E2]', label: 'Alarm' },
  { id: 'calendar', icon: CalendarDays, color: 'text-[#166534]', background: 'bg-[#DCFCE7]', label: 'Calendar' },
  { id: 'moon', icon: Moon, color: 'text-[#9CA3AF]', background: 'bg-[#F3F4F6]', label: 'Moon' },
  { id: 'umbrella', icon: Umbrella, color: 'text-[#0284C7]', background: 'bg-[#E0F2FE]', label: 'Umbrella' },
  { id: 'atom', icon: Atom, color: 'text-[#0E7490]', background: 'bg-[#CFFAFE]', label: 'Atom' },
  { id: 'beaker', icon: Beaker, color: 'text-[#3730A3]', background: 'bg-[#E0E7FF]', label: 'Beaker' },
  { id: 'bug', icon: Bug, color: 'text-[#B91C1C]', background: 'bg-[#FEE2E2]', label: 'Bug' },
  { id: 'cat', icon: Cat, color: 'text-[#EA580C]', background: 'bg-[#FFEDD5]', label: 'Cat' },
  { id: 'dog', icon: Dog, color: 'text-[#A16207]', background: 'bg-[#FEF9C3]', label: 'Dog' },
  { id: 'dice', icon: Dice5, color: 'text-[#6B21A8]', background: 'bg-[#F3E8FF]', label: 'Dice' },
  { id: 'eye', icon: Eye, color: 'text-[#F9A8D4]', background: 'bg-[#FCE7F3]', label: 'Eye' },
  { id: 'feather', icon: Feather, color: 'text-[#6EE7B7]', background: 'bg-[#D1FAE5]', label: 'Feather' },
  { id: 'file', icon: FileText, color: 'text-[#0E7490]', background: 'bg-[#CFFAFE]', label: 'Document' },
  { id: 'film', icon: Film, color: 'text-[#86198F]', background: 'bg-[#FAE8FF]', label: 'Film' },
  { id: 'flag', icon: Flag, color: 'text-[#65A30D]', background: 'bg-[#ECFCCB]', label: 'Flag' },
  { id: 'gamepad', icon: Gamepad2, color: 'text-[#F87171]', background: 'bg-[#FEE2E2]', label: 'Game' },
  { id: 'ghost', icon: Ghost, color: 'text-[#374151]', background: 'bg-[#E5E7EB]', label: 'Ghost' },
  { id: 'git-branch', icon: GitBranch, color: 'text-[#A855F7]', background: 'bg-[#F3E8FF]', label: 'Branch' },
  { id: 'git-commit', icon: GitCommit, color: 'text-[#1E3A8A]', background: 'bg-[#E0E7FF]', label: 'Commit' },
  { id: 'globe1', icon: Globe, color: 'text-[#0891B2]', background: 'bg-[#CFFAFE]', label: 'World' },
  { id: 'home', icon: Home, color: 'text-[#4D7C0F]', background: 'bg-[#ECFCCB]', label: 'Home' },
  { id: 'laptop', icon: Laptop, color: 'text-[#4F46E5]', background: 'bg-[#E0E7FF]', label: 'Laptop' },
  { id: 'library', icon: Library, color: 'text-[#15803D]', background: 'bg-[#DCFCE7]', label: 'Library' },
  { id: 'lock', icon: Lock, color: 'text-[#374151]', background: 'bg-[#E5E7EB]', label: 'Lock' },
  { id: 'magnet', icon: Magnet, color: 'text-[#DB2777]', background: 'bg-[#FCE7F3]', label: 'Magnet' },
  { id: 'map', icon: Map, color: 'text-[#16A34A]', background: 'bg-[#DCFCE7]', label: 'Map' },
  { id: 'mic', icon: Mic, color: 'text-[#C084FC]', background: 'bg-[#F3E8FF]', label: 'Mic' },
  { id: 'monitor', icon: Monitor, color: 'text-[#1D4ED8]', background: 'bg-[#DBEAFE]', label: 'Monitor' },
  { id: 'mouse', icon: MousePointer, color: 'text-[#92400E]', background: 'bg-[#FFFBEB]', label: 'Pointer' },
  { id: 'mountain', icon: Mountain, color: 'text-[#6B7280]', background: 'bg-[#F3F4F6]', label: 'Mountain' },
  { id: 'pen', icon: PenTool, color: 'text-[#4ADE80]', background: 'bg-[#DCFCE7]', label: 'Pen Tool' },
  { id: 'phone', icon: Phone, color: 'text-[#166534]', background: 'bg-[#DCFCE7]', label: 'Phone' },
  { id: 'piggy', icon: PiggyBank, color: 'text-[#F472B6]', background: 'bg-[#FCE7F3]', label: 'Piggy Bank' },
  { id: 'pin', icon: Pin, color: 'text-[#06B6D4]', background: 'bg-[#CFFAFE]', label: 'Pin' },
  { id: 'pizza', icon: Pizza, color: 'text-[#F97316]', background: 'bg-[#FFEDD5]', label: 'Pizza' },
  { id: 'plug', icon: Plug, color: 'text-[#0369A1]', background: 'bg-[#E0F2FE]', label: 'Plug' },
  { id: 'rainbow', icon: Rainbow, color: 'text-[#F472B6]', background: 'bg-[#FCE7F3]', label: 'Rainbow' },
  { id: 'recycle', icon: Recycle, color: 'text-[#15803D]', background: 'bg-[#DCFCE7]', label: 'Recycle' },
  { id: 'scroll', icon: Scroll, color: 'text-[#FCD34D]', background: 'bg-[#FEF9C3]', label: 'Scroll' },
  { id: 'send', icon: Send, color: 'text-[#1D4ED8]', background: 'bg-[#DBEAFE]', label: 'Send' },
  { id: 'server', icon: Server, color: 'text-[#3730A3]', background: 'bg-[#E0E7FF]', label: 'Server' },
  { id: 'settings', icon: Settings, color: 'text-[#4B5563]', background: 'bg-[#F3F4F6]', label: 'Settings' },
  { id: 'shopping', icon: ShoppingCart, color: 'text-[#C2410C]', background: 'bg-[#FFEDD5]', label: 'Shopping Cart' },
  { id: 'smile', icon: Smile, color: 'text-[#FDE047]', background: 'bg-[#FEFCE8]', label: 'Smile' },
  { id: 'snowflake', icon: Snowflake, color: 'text-[#93C5FD]', background: 'bg-[#DBEAFE]', label: 'Snowflake' },
  { id: 'sparkle', icon: Sparkle, color: 'text-[#A5B4FC]', background: 'bg-[#E0E7FF]', label: 'Sparkle' },
  { id: 'speech', icon: Speech, color: 'text-[#DB2777]', background: 'bg-[#FCE7F3]', label: 'Speech' },
  { id: 'sun-medium', icon: SunMedium, color: 'text-[#FDBA74]', background: 'bg-[#FFEDD5]', label: 'Sun Medium' },
  { id: 'target', icon: Target, color: 'text-[#DC2626]', background: 'bg-[#FEE2E2]', label: 'Target' },
  { id: 'terminal', icon: Terminal, color: 'text-[#525252]', background: 'bg-[#E5E7EB]', label: 'Terminal' },
  { id: 'thumbsup', icon: ThumbsUp, color: 'text-[#3B82F6]', background: 'bg-[#DBEAFE]', label: 'Thumbs Up' },
  { id: 'timer', icon: Timer, color: 'text-[#34D399]', background: 'bg-[#D1FAE5]', label: 'Timer' },
  { id: 'tree', icon: TreePine, color: 'text-[#22C55E]', background: 'bg-[#DCFCE7]', label: 'Pine Tree' },
  { id: 'wallet', icon: Wallet, color: 'text-[#A16207]', background: 'bg-[#FEF9C3]', label: 'Wallet' },
  { id: 'wand', icon: Wand2, color: 'text-[#D8B4FE]', background: 'bg-[#F3E8FF]', label: 'Wand' },
  { id: 'wind', icon: Wind, color: 'text-[#67E8F9]', background: 'bg-[#CFFAFE]', label: 'Wind' },
  { id: 'wrench', icon: Wrench, color: 'text-[#374151]', background: 'bg-[#E5E7EB]', label: 'Wrench' },
]
;
